stages:
    - "test"

test:
    image: "python:3.7"
    stage: "test"
    script:
       - pip install -r requirements.txt
       - py.test --cov
       - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

pages:
  stage: .post
  script:
  - pip install -U sphinx
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
