stages:
    - "test"

test:
    image: "python:3.7"
    stage: "test"
    script:
       - pip install -r requirements.txt
       - pytest tests --with-coverage
       - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
