stages:
    - "test"

include:
  - template: Code-Quality.gitlab-ci.yml

test:
    image: "python:3.7"
    stage: "test"
    script:
       - pip install -r requirements.txt
       - py.test --cov
       - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

code_quality:
  stage: test
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [gl-code-quality-report.json]
